import type { RequestStatus } from "./contracts";
export const intentLabels: Record<string, string> = {
  DEVICE_SHUTDOWN_GUIDANCE: "Tắt máy",
  DEVICE_RESTART_GUIDANCE: "Khởi động lại máy",
  DEVICE_RESET_GUIDANCE: "Đặt lại máy (chưa rõ cách)",
  DEVICE_FACTORY_RESET: "Khôi phục cài đặt gốc",
  DEVICE_WONT_BOOT: "Máy không khởi động",
  DEVICE_FREEZE: "Máy bị treo",
  DEVICE_SLOW: "Máy chạy chậm",
  DEVICE_CRASH: "Máy bị lỗi đột ngột",
  DEVICE_UPDATE_DRIVER: "Cập nhật trình điều khiển",
  DEVICE_BATTERY: "Vấn đề về pin",
  DEVICE_DISPLAY: "Màn hình",
  DEVICE_AUDIO: "Âm thanh",
  DEVICE_CAMERA: "Camera",
  DEVICE_PRINTER: "Máy in",
  DEVICE_LOST_STOLEN: "Mất hoặc bị đánh cắp thiết bị",
  DEVICE_REPLACEMENT: "Thay thiết bị",
  DEVICE_WIPE: "Xóa toàn bộ thiết bị",
  ACCOUNT_LOGIN: "Đăng nhập tài khoản",
  ACCOUNT_LOCKED: "Tài khoản bị khóa",
  PASSWORD_RESET: "Đặt lại mật khẩu cá nhân",
  MFA_SETUP: "Thiết lập xác thực hai bước",
  MFA_FAILURE: "Lỗi xác thực hai bước",
  SSO_FAILURE: "Lỗi đăng nhập một lần",
  REQUEST_STANDARD_ACCESS: "Xin quyền thông thường",
  REQUEST_READ_ACCESS: "Xin quyền chỉ xem",
  REQUEST_WRITE_ACCESS: "Xin quyền chỉnh sửa",
  REQUEST_ADMIN_ACCESS: "Xin quyền quản trị",
  REQUEST_ROOT_ACCESS: "Xin quyền cao nhất",
  GROUP_MEMBERSHIP: "Tham gia nhóm",
  ROLE_CHANGE: "Đổi vai trò",
  REVOKE_ACCESS: "Thu hồi quyền",
  SERVICE_ACCOUNT: "Tài khoản dịch vụ",
  ACCOUNT_DEACTIVATION: "Ngừng tài khoản",
  DATABASE_CONNECTION: "Kết nối cơ sở dữ liệu",
  DATABASE_READ_ACCESS: "Xin quyền chỉ đọc dữ liệu",
  DATABASE_WRITE_ACCESS: "Xin quyền ghi dữ liệu",
  DATABASE_QUERY_HELP: "Hướng dẫn câu truy vấn",
  DATABASE_QUERY_ERROR: "Câu truy vấn bị lỗi",
  DATABASE_PERFORMANCE: "Hiệu năng cơ sở dữ liệu",
  DATABASE_PROVISION: "Tạo cơ sở dữ liệu",
  DATABASE_SCHEMA_CHANGE: "Thay cấu trúc dữ liệu",
  DATABASE_DATA_CORRECTION: "Sửa dữ liệu",
  DATABASE_EXPORT: "Xuất dữ liệu",
  DATABASE_IMPORT: "Nhập dữ liệu",
  DATABASE_BACKUP: "Sao lưu cơ sở dữ liệu",
  DATABASE_RESTORE: "Khôi phục cơ sở dữ liệu",
  DATABASE_MIGRATION: "Di chuyển cơ sở dữ liệu",
  DATABASE_PRODUCTION_INCIDENT: "Sự cố dữ liệu đang vận hành",
  VPN_SETUP: "Cài đặt VPN",
  VPN_LOGIN: "Đăng nhập VPN",
  VPN_NOT_CONNECTING: "VPN không kết nối",
  WIFI_NOT_WORKING: "Wi-Fi không hoạt động",
  NETWORK_UNREACHABLE: "Không truy cập được mạng",
  DNS_RESOLUTION: "Tra cứu tên miền",
  DNS_CHANGE: "Thay đổi DNS",
  PROXY_CONFIG: "Cấu hình máy chủ trung gian",
  FIREWALL_DIAGNOSTIC: "Kiểm tra tường lửa",
  FIREWALL_CHANGE: "Thay đổi tường lửa",
  PORT_OPEN_REQUEST: "Mở cổng kết nối",
  PUBLIC_EXPOSURE: "Cho phép truy cập từ Internet",
  REMOTE_ACCESS: "Truy cập máy từ xa",
  BANDWIDTH_ISSUE: "Mạng chậm",
  CERTIFICATE_ERROR: "Lỗi chứng chỉ kết nối",
  SOFTWARE_INSTALL: "Cài phần mềm",
  SOFTWARE_UPDATE: "Cập nhật phần mềm",
  SOFTWARE_UNINSTALL: "Gỡ phần mềm",
  SOFTWARE_CRASH: "Phần mềm bị lỗi",
  SOFTWARE_COMPATIBILITY: "Phần mềm không tương thích",
  SOFTWARE_PERFORMANCE: "Phần mềm chạy chậm",
  LICENSE_ACTIVATION: "Kích hoạt bản quyền",
  LICENSE_REQUEST: "Xin bản quyền",
  APPROVED_CATALOG_LOOKUP: "Tra cứu phần mềm được phép",
  BROWSER_EXTENSION: "Tiện ích trình duyệt",
  UNSIGNED_SOFTWARE: "Phần mềm không có chữ ký",
  UNAPPROVED_SOFTWARE: "Phần mềm chưa được cho phép",
  DEVELOPER_TOOL_SETUP: "Cài công cụ lập trình",
  CLOUD_SANDBOX: "Môi trường thử nghiệm",
  CLOUD_VM_REQUEST: "Xin máy chủ ảo",
  GPU_REQUEST: "Xin GPU",
  GPU_QUOTA: "Tăng hạn mức GPU",
  GPU_CAPACITY: "Kiểm tra GPU còn trống",
  CLOUD_STORAGE: "Lưu trữ đám mây",
  CLOUD_COST: "Chi phí đám mây",
  CLOUD_BUDGET: "Ngân sách đám mây",
  PUBLIC_IP: "IP công khai",
  RESOURCE_SCALE: "Thay đổi quy mô tài nguyên",
  RESOURCE_DELETE: "Xóa tài nguyên",
  CLOUD_CREDENTIAL: "Thông tin truy cập đám mây",
  K8S_VIEW_LOGS: "Xem nhật ký ứng dụng",
  K8S_VIEW_METRICS: "Xem số liệu ứng dụng",
  K8S_RESTART_POD: "Khởi động lại ứng dụng",
  K8S_SCALE_WORKLOAD: "Đổi số bản chạy",
  K8S_NAMESPACE_REQUEST: "Xin không gian làm việc",
  K8S_DEPLOY: "Triển khai ứng dụng",
  K8S_MANIFEST_CHANGE: "Thay cấu hình ứng dụng",
  K8S_ROLLBACK: "Quay về phiên bản cũ",
  K8S_EXEC_POD: "Chạy lệnh trong ứng dụng",
  K8S_CLUSTER_ACCESS: "Xin quyền vào cụm",
  K8S_SECRET_ACCESS: "Truy cập thông tin bí mật",
  K8S_INGRESS_CHANGE: "Thay luồng truy cập vào",
  K8S_CLUSTER_ADMIN: "Quản trị toàn bộ cụm",
  PIPELINE_VIEW_LOGS: "Xem nhật ký triển khai",
  PIPELINE_RERUN: "Chạy lại quy trình",
  PIPELINE_FAILED: "Quy trình bị lỗi",
  PIPELINE_PERMISSION: "Xin quyền quy trình",
  PIPELINE_CONFIG_CHANGE: "Thay cấu hình quy trình",
  STAGING_DEPLOY: "Triển khai môi trường kiểm thử",
  PRODUCTION_DEPLOY: "Triển khai hệ thống thật",
  PRODUCTION_ROLLBACK: "Khôi phục hệ thống thật",
  SECRET_UPDATE: "Cập nhật thông tin bí mật",
  RELEASE_APPROVAL: "Xin duyệt phát hành",
  BYPASS_APPROVAL_GATE: "Bỏ qua bước phê duyệt",
  MONITORING_VIEW_LOGS: "Xem nhật ký giám sát",
  MONITORING_VIEW_METRICS: "Xem số liệu giám sát",
  ALERT_NOT_RECEIVED: "Không nhận được cảnh báo",
  ALERT_FALSE_POSITIVE: "Cảnh báo nhầm",
  ALERT_THRESHOLD: "Thay ngưỡng cảnh báo",
  ALERT_ROUTING: "Đổi người nhận cảnh báo",
  INCIDENT_REPORT: "Báo sự cố",
  INCIDENT_TRIAGE: "Đánh giá sự cố",
  SERVICE_DEGRADED: "Dịch vụ hoạt động chậm",
  SERVICE_OUTAGE: "Dịch vụ ngừng hoạt động",
  P1_INCIDENT: "Sự cố nghiêm trọng P1",
  P2_INCIDENT: "Sự cố nghiêm trọng P2",
  SLO_BREACH: "Không đạt mục tiêu chất lượng",
  STORAGE_ACCESS: "Xin quyền lưu trữ",
  STORAGE_QUOTA: "Tăng dung lượng",
  FILE_SHARE: "Chia sẻ tệp",
  BUCKET_ACCESS: "Xin quyền vùng lưu trữ",
  BACKUP_REQUEST: "Yêu cầu sao lưu",
  BACKUP_FAILURE: "Sao lưu bị lỗi",
  RESTORE_REQUEST: "Yêu cầu khôi phục",
  DATA_RECOVERY: "Cứu dữ liệu",
  DATA_DELETE: "Xóa dữ liệu",
  DATA_RETENTION: "Thời hạn lưu dữ liệu",
  DATA_EXPORT: "Xuất dữ liệu",
  ARCHIVE_REQUEST: "Lưu trữ lâu dài",
  PHISHING_REPORT: "Báo thư lừa đảo",
  MALWARE_SUSPECTED: "Nghi có mã độc",
  SUSPICIOUS_LOGIN: "Đăng nhập đáng ngờ",
  LOST_DEVICE_SECURITY: "Mất thiết bị có dữ liệu",
  SECRET_EXPOSURE: "Lộ thông tin bí mật",
  CREDENTIAL_LEAK: "Lộ thông tin đăng nhập",
  VULNERABILITY_REPORT: "Báo lỗ hổng",
  POLICY_EXCEPTION: "Xin ngoại lệ chính sách",
  MFA_DISABLE_REQUEST: "Tắt xác thực hai bước",
  EDR_DISABLE_REQUEST: "Tắt bảo vệ thiết bị",
  SECURITY_INCIDENT: "Sự cố bảo mật",
  DATA_BREACH: "Rò rỉ dữ liệu",
  AUDIT_EVIDENCE: "Bằng chứng kiểm tra",
  COMPLIANCE_QUESTION: "Hỏi về quy định",
  GIT_READ_ACCESS: "Xin quyền đọc mã nguồn",
  GIT_WRITE_ACCESS: "Xin quyền sửa mã nguồn",
  GIT_ADMIN_ACCESS: "Xin quyền quản trị kho",
  GIT_HELP: "Hướng dẫn sử dụng Git",
  UNKNOWN_SUPPORT_REQUEST: "Chưa xác định vấn đề",
  GENERAL_HOW_TO: "Hỏi cách thực hiện",
  CROSS_FUNCTION_REQUEST: "Vấn đề liên quan nhiều nhóm",
  UNCLASSIFIED_ACCESS: "Xin quyền chưa rõ loại",
  UNCLASSIFIED_INCIDENT: "Báo sự cố chưa rõ loại",
  UNCLASSIFIED_CHANGE: "Thay đổi chưa rõ loại",
  REQUEST_CLASSIFICATION_HELP: "Nhờ xác định nhóm hỗ trợ",
};
const optionLabels: Record<string, string> = {
  it: "Công nghệ thông tin",
  engineering: "Kỹ thuật",
  product: "Sản phẩm",
  sales: "Kinh doanh",
  marketing: "Marketing",
  finance: "Tài chính",
  human_resources: "Nhân sự",
  operations: "Vận hành",
  other: "Khác",
  factory_reset: "Khôi phục cài đặt gốc (có thể mất dữ liệu)",
  unknown: "Tôi không biết",
  Unknown: "Tôi không biết",
  not_provided: "Chưa cung cấp",
  no: "Không",
  No: "Không",
  yes: "Có",
  Yes: "Có",
  sandbox: "Thử nghiệm riêng",
  development: "Phát triển",
  staging: "Kiểm thử",
  production: "Đang vận hành thật",
  Laptop: "Máy tính xách tay",
  Desktop: "Máy tính để bàn",
  Monitor: "Màn hình",
  Printer: "Máy in",
  Mobile: "Điện thoại",
  Other: "Khác",
  Personal: "Cá nhân",
  Corporate: "Công ty",
  Shared: "Dùng chung",
  guidance: "Hướng dẫn",
  diagnose: "Kiểm tra lỗi",
  restart: "Khởi động lại",
  repair: "Sửa chữa",
  replace: "Thay mới",
  wipe: "Xóa toàn bộ",
  view_logs: "Xem nhật ký",
  rerun: "Chạy lại",
  deploy: "Triển khai",
  change: "Thay đổi",
  "read-only": "Chỉ xem",
  read: "Đọc",
  standard: "Thông thường",
  write: "Chỉnh sửa",
  admin: "Quản trị",
  root: "Quyền cao nhất",
  owner: "Chủ sở hữu",
  maintain: "Bảo trì",
  "cluster-admin": "Quản trị toàn cụm",
  provision: "Tạo tài nguyên",
  query_help: "Hướng dẫn truy vấn",
  export: "Xuất dữ liệu",
  import: "Nhập dữ liệu",
  backup: "Sao lưu",
  restore: "Khôi phục",
  delete: "Xóa",
  normal: "Bình thường",
  low: "Thấp",
  high: "Cao",
  critical: "Rất khẩn cấp",
  claimed: "Tôi đã được đồng ý (cần xác minh)",
  pending: "Đang chờ duyệt",
  synthetic: "Dữ liệu giả lập",
  internal: "Nội bộ",
  customer: "Khách hàng",
  confidential: "Bảo mật",
  approved: "Được cho phép",
  unapproved: "Chưa được cho phép",
};
export const statusLabels: Record<RequestStatus, string> = {
  RECEIVED: "Đã tiếp nhận",
  PROCESSING: "Đang xử lý",
  AUTO_APPROVED: "Đã có hướng dẫn hoặc phương án",
  NEEDS_INFORMATION: "Cần bạn bổ sung thông tin",
  ESCALATED: "Đang chờ nhân viên hỗ trợ",
  APPROVED_BY_HUMAN: "Nhân viên đã duyệt",
  REJECTED: "Yêu cầu đã bị từ chối",
  STOPPED: "Đã dừng xử lý",
  COMPLETED: "Đã hoàn tất",
};
export const intentName = (value: string) =>
  intentLabels[value] ?? "Nhu cầu hỗ trợ";
export const optionName = (value: string) => optionLabels[value] ?? value;
export const displayId = (id: string) => "HT-" + id.slice(0, 8).toUpperCase();
