import Link from "next/link";
export default function Help() {
  return <main className="identity-page identity-guide"><article className="identity-card"><span className="eyebrow">HƯỚNG DẪN VNG SUPPORT</span><h1>Bắt đầu từ việc bạn cần làm</h1><nav className="identity-links" aria-label="Mục lục hướng dẫn"><a href="#login">Đăng nhập</a><a href="#new">Xin cấp ID</a><a href="#support">Gửi hỗ trợ</a><a href="#review">Xử lý & Verify</a></nav>
    <section id="login"><h2>Đăng nhập bằng ID</h2><p>Chọn “Tôi cần hỗ trợ” ở trang đầu, rồi tại <Link href="/login">Đăng nhập</Link>, nhập ID chính thức rồi chọn Đăng nhập. “Hướng dẫn & tùy chọn” chứa theo dõi đơn cấp ID, hướng dẫn demo và lối vào trải nghiệm bằng dữ liệu giả lập. Không có mật khẩu. Theo cấu hình demo hiện tại, ID đã cấp và còn hiệu lực được vào gửi hỗ trợ mà không cần OTP; ID chưa cấp hoặc đã vô hiệu hóa sẽ bị từ chối.</p><p>Biết ID không chứng minh danh tính. Phiên demo không cấp quyền IT hoặc quyền thực thi tài nguyên. Người xử lý ID mở “Dành cho người xử lý ID”, chọn xác minh OTP. Mã 6 số có hiệu lực 5 phút, tối đa 5 lần thử và chỉ dùng một lần. Kênh nhận mã do IT xác minh và cấu hình trước; form công khai không thu thập liên hệ. Chưa cấu hình kênh thì chưa thể xác minh quyền IT. Phiên hết hạn sau 8 giờ; dùng Đăng xuất khi dùng máy chung.</p></section>
    <section id="new"><h2>Nhân viên mới: xin cấp ID</h2><ol><li>Chọn <Link href="/identity/new">Nhân viên mới?</Link> dưới ô đăng nhập. Nhập họ tên người cần cấp ID.</li><li>Chọn job có sẵn hoặc Tạo job mới. Job có sẵn giữ đúng phạm vi của phiên bản profile; IT duyệt việc gắn profile đó. Job mới cần tên job và các phạm vi đề xuất, IT chọn phạm vi phù hợp trước khi tạo profile.</li><li>Với mỗi phạm vi, chọn môi trường, tài nguyên, thao tác và đích cụ thể, rồi bấm Thêm phạm vi. Ví dụ dữ liệu giả lập: sandbox → task/dự án → đọc → project-demo/task-01. Không nhập dấu *, “all”, giá trị secrets hoặc quyền tự do.</li><li>Xem lại thông tin rồi Gửi đơn cho IT. Nếu MongoDB lỗi, đơn chưa được xác nhận lưu; giữ trang và thử lại cùng đơn khi kết nối phục hồi.</li><li>Lưu liên kết riêng trong biên nhận để <Link href="/identity/track">theo dõi đơn cấp ID</Link>. Liên kết cho phép đọc đơn, không cấp phiên đăng nhập. Không chia sẻ công khai.</li></ol><p>Chờ IT: chưa cấp ID. Trùng ID: IT xác minh và chọn hậu tố số có lý do, ví dụ ID gốc-2; không ghi đè tài khoản. Từ chối: trang theo dõi hiển thị lý do để bạn gửi đơn mới phù hợp. Được duyệt: trang thành công mới hiển thị ID chính thức và nút về đăng nhập.</p><p>ID lấy tên cuối không dấu rồi nối chữ đầu các từ trước: Phạm Quang Minh Hòa → hoapqm; Trần Ngọc Anh → anhtn. Đây là ví dụ quy tắc, không phải tài khoản đã cấp.</p><p>Production, secrets, khóa, quản trị/root, xuất dữ liệu và các thao tác nhạy cảm luôn được đánh dấu; duyệt job chưa cho phép thực thi. Mọi kiểm tra phạm vi ở server. Hệ thống hiện ghi nhận và kiểm tra quyền, chưa kết nối IAM để cấp quyền vào tài nguyên thật. Danh mục là cơ chế đề xuất của dự án, không phải policy chính thức của VNG.</p></section>
    <section id="support"><h2>Gửi và theo dõi yêu cầu hỗ trợ</h2><ol><li>Vào <Link href="/send-help">Gửi yêu cầu</Link>. Phiên đăng nhập tự điền ID. Luồng demo cho giám khảo vẫn cho nhập mã giả lập và phòng ban.</li><li>Mô tả vấn đề bằng lời hoặc chọn theo danh mục. Bắt đầu với những gì bạn biết; bổ sung trường nâng cao khi cần.</li><li>Bấm Gửi để xem trước kết quả. Kiểm tra, sửa nếu cần, rồi Xác nhận và gửi yêu cầu hoặc Lưu và tiếp tục trò chuyện. Xem trước chưa tạo yêu cầu đã lưu.</li><li>Lưu liên kết yêu cầu hoặc mở <Link href="/track">Theo dõi yêu cầu hỗ trợ</Link>. Trả lời câu hỏi làm rõ, hỏi tiếp, phản hồi đã giải quyết/vẫn lỗi hoặc chuyển nhân viên.</li></ol><p>Deterministic policy quyết định giới hạn cuối cùng. AI chỉ hỗ trợ trích xuất và giải thích. Sentiment sau câu trả lời không mở đường cho thao tác nguy hiểm. Nút URL & QR giúp mở app trên điện thoại.</p></section>
    <section id="review"><h2>Người xử lý và giám khảo</h2><p><Link href="/review">Yêu cầu cần xử lý</Link> giữ bộ lọc, tìm mã HT, phân loại cần thẩm quyền/ngoài quy định, gợi ý tri thức và xử lý có lý do. <Link href="/audit">Lịch sử xử lý</Link> cho phép đối chiếu audit. Đây là không gian hỗ trợ demo; quyền duyệt ID tách riêng ở <Link href="/identity/review">Cấp ID nhân viên</Link> và bắt buộc phiên OTP cùng vai trò do operator cấp.</p><p><Link href="/verify">Verify / Kiểm thử</Link> giữ bộ 5 trường hợp Đề A, bộ 15 tình huống và tiếp nhận input mới theo brief. Chỉ dùng dữ liệu giả lập. Kết quả mock/local không chứng minh model thật, người dùng thực, policy VNG hoặc production.</p></section>
    <section><h2>Khi gặp lỗi</h2><ul><li>ID không hợp lệ: kiểm tra ID chính thức trong đơn, không dùng ID dự đoán trước khi được duyệt.</li><li>MongoDB chưa cấu hình/không khả dụng: không có memory hoặc CSV thay thế cho hệ thống ID; liên hệ IT và thử lại.</li><li>Phiên hết hạn: đăng nhập lại. Quyền IT bị từ chối: kiểm tra phiên OTP và vai trò được operator cấp.</li><li>Đơn đã thay đổi: IT tải lại danh sách trước khi quyết định; hệ thống chặn ghi đè quyết định ở tab khác.</li></ul><p>Cấu hình vận hành MongoDB replica set, bootstrap IT và OTP relay được mô tả trong README và RUNBOOK của repository. Không nhập credentials vào giao diện hoặc gửi chúng trong yêu cầu hỗ trợ.</p></section>
  </article></main>;
}
